# Generated by Django 4.2.7 on 2023-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('price', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=300)),
                ('link_to_product', models.CharField(max_length=700)),
                ('info_about_product', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
