# Generated by Django 4.2.7 on 2023-12-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='buying_method',
            field=models.CharField(default='default', max_length=20),
        )
    ]
