# Generated by Django 4.2.7 on 2023-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_goods_orders_buying_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
